# DataSource
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
      username : root
      password : root123
#tomcat
server:
  port: 8070